import "./global.css";
import Nav from "@/components/Nav";
import { Instrument_Sans } from "next/font/google";
import frontend from "../public/images/icon-frontend-mentor.svg";

export const metadata = {
  title: "Frontend Mentor | DevLinks",
  description: "Generated by Next.js",
};

const font = Instrument_Sans({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
