import "./global.css";
import { Instrument_Sans } from "next/font/google";

export const metadata = {
  title: "Frontend Mentor | DevLinks",
  description: "Generated by Next.js",
};

const font = Instrument_Sans({ subsets: ["latin"], preload: false });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
