import "../app/global.css";
import Nav from "./Nav";
import { Instrument_Sans } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Instrument_Sans({ subsets: ["latin"] });

export default function Layout({ children }) {
  return (
    <main className={font.className}>
      <Nav />
      {children}
    </main>
  );
}
